# Use an official Node.js runtime as a base image
FROM node:20.11.1

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install -g npm@10.9.0
RUN npm install --force
# Copy the rest of the application code
COPY . .

# Expose port 3000 for the Node.js app
EXPOSE 3000

# Default command
CMD ["node", "server.js"]
