# Use an official Node.js runtime as a base image for building Angular app
FROM node:20.11.1 as builder

# Set the working directory in the container
ARG WORK_DIR='/app'
USER 0
WORKDIR $WORK_DIR
# Copy package.json and package-lock.json to the container
COPY package*.json /app/

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install application dependencies
RUN npm install

RUN npm ci

# Copy the entire application code to the container
COPY . .

# Build the Angular app
RUN ng build

# Use Nginx as a base image to serve the Angular app
FROM registry.access.redhat.com/ubi8/nginx-120
USER 0
RUN dnf update -y && dnf upgrade -y
USER 1001

# Copy Nginx configuration
ARG WORK_DIR='/app'
COPY --chown=1001:0 nginx/nginx.conf "${NGINX_CONF_PATH}"

# Copy the built Angular app from the previous stage to the nginx public directory
# COPY --from=builder /app/dist/browser /usr/share/nginx/html
COPY --from=builder --chown=1001:0 $WORK_DIR/dist/browser .
RUN chmod -R 775 .

# Expose port 80 for the Angular app
EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]