version: '3.8'
services:
  angular-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - '80:80'
    depends_on:
      - node-backend

  node-backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '3000:3000'
    depends_on:
      - postgres-db
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: myappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: myappdb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      # any .sql/.sh in ./scripts/db will be run at container start
      - ./scripts/db:/docker-entrypoint-initdb.d
