version: '3'
services:

  angular-frontend:
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
      - "80:4200"
    # depends_on:
    #   - node-backend

  # node-backend:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.node
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres-db

  # postgres-db:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d