# Stage 1: deps & cache
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps

# Stage 2: final
FROM node:20-alpine
WORKDIR /app

# bring in deps
COPY --from=deps /app/node_modules ./node_modules

# copy app code
COPY . .

EXPOSE 3000
CMD ["node", "server.js"]
